var LoremIpsum = (function () {
    var VERSION = '0.0.1',

    sentence = function () {
        return "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },

    paragraph = function () {
        var sentences = [
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean quis lorem vitae eros vulputate pharetra a non justo. Morbi imperdiet quam eu elit sollicitudin posuere. Integer eget magna ornare odio porta varius non sed augue. Ut auctor, tortor id congue luctus, lorem ante efficitur purus, in euismod orci neque et felis. Morbi ut convallis libero, in bibendum magna. Quisque non odio vitae diam aliquam rutrum at ac sapien. Suspendisse id lorem vel ex aliquet luctus. Vivamus vulputate massa non dapibus eleifend. Sed sed tincidunt diam. Vivamus nunc metus, hendrerit eget purus quis, fringilla volutpat sapien. Mauris enim tortor, tincidunt eget porttitor et, fringilla vel metus. In hac habitasse platea dictumst. Integer in massa dapibus massa auctor consequat a at sapien.",
            "Morbi viverra feugiat enim, sed fermentum diam malesuada eu. Praesent vel mi pharetra, iaculis erat vestibulum, maximus est. Curabitur quis risus arcu. Donec porttitor lorem nec nulla imperdiet, non consequat libero pellentesque. Proin enim risus, commodo ut tempor ac, finibus non est. Curabitur condimentum vulputate massa at imperdiet. Nullam nec egestas felis. Sed pulvinar enim id erat gravida laoreet.",
            "Maecenas finibus non orci at vulputate. Curabitur lacus felis, posuere ac pellentesque eget, convallis id mauris. Aliquam pulvinar blandit nisi ut aliquam. Vivamus suscipit ante vel mi mollis, consequat volutpat dui dapibus. Sed id vestibulum lectus, vitae mattis orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse laoreet, nunc non vestibulum lacinia, est justo suscipit orci, eu fringilla lorem mi sed dolor. Morbi cursus faucibus felis non sodales. Vestibulum eget mattis mi. Nam at ultrices dui, eget blandit purus. Aenean convallis suscipit est, non vestibulum orci euismod sit amet. Cras sed enim volutpat, ullamcorper lorem sagittis, tempus justo. Quisque fringilla diam sit amet purus placerat, eget gravida dui consequat. In quis leo eget ex ullamcorper rutrum nec sed diam. Praesent volutpat vulputate egestas.",
            "Sed semper nibh sed arcu tempor, a consequat lectus interdum. Etiam at ullamcorper lectus, tristique consectetur ante. Mauris sodales, orci eu suscipit fringilla, mauris ligula mollis purus, a ullamcorper purus justo et ipsum. Aliquam erat volutpat. Nunc ullamcorper magna eu nibh pretium, eu volutpat quam tincidunt. Proin at imperdiet diam, nec tempus lectus. In non neque mauris. Vestibulum tristique mauris neque, in faucibus sapien tincidunt et. Nulla sollicitudin massa ex, id semper nunc aliquet id. Praesent at tortor sed sapien ullamcorper ullamcorper. Morbi ac nunc dictum, vestibulum mi eget, tristique neque. Morbi sagittis vitae libero vestibulum interdum. Praesent pulvinar tristique egestas. Aenean at enim et ipsum euismod accumsan.",
            "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam fringilla mattis tellus tempus malesuada. Praesent aliquet elementum justo, vel scelerisque augue egestas non. Proin et ullamcorper dolor. Sed hendrerit metus vitae dui tristique iaculis. Cras varius mi at lacus facilisis, eu pulvinar diam pulvinar. Suspendisse potenti. Morbi facilisis, velit ut sagittis laoreet, orci nunc ornare felis, vel dignissim nunc sem quis enim. Cras mauris purus, sagittis sit amet maximus a, rhoncus at magna. Pellentesque id orci vitae dolor iaculis molestie sit amet eu nisl. Ut euismod aliquam volutpat. Nam laoreet orci sed tincidunt consequat. Donec nisl est, semper at erat in, malesuada fringilla tortor.",
            "Mauris vel nisi quis est scelerisque dictum. Donec interdum, ligula maximus egestas viverra, orci purus volutpat mi, nec consequat tortor eros in quam. Mauris fringilla leo ligula, at pellentesque metus posuere sit amet. Sed rutrum congue arcu ac tristique. Integer iaculis est quis turpis rutrum pulvinar vitae a nibh. Donec imperdiet a elit sed sagittis. Maecenas auctor velit ligula, non scelerisque ipsum convallis et. Sed pretium nulla sed tortor eleifend, ac vestibulum ipsum accumsan. Aenean tincidunt, tellus non mattis maximus, dolor eros gravida erat, a sollicitudin purus leo eget dui. Sed quis imperdiet eros. Nulla erat nisl, fermentum viverra augue in, faucibus euismod libero. Vivamus dignissim eget lectus id iaculis. Morbi vel enim massa.",
            "Curabitur euismod tristique vestibulum. Ut interdum mauris eget nulla ultricies, nec malesuada diam feugiat. Donec ut sodales ex, sed cursus ipsum. Duis aliquet iaculis orci, vitae laoreet metus lacinia at. Sed mattis nec nunc sit amet luctus. In sit amet nisl nec ligula laoreet mattis. Nullam lobortis mi non quam tristique, ut aliquam mauris ultrices. Fusce tincidunt lacus vel orci tincidunt ultrices. Sed massa diam, sodales ut turpis et, consectetur accumsan turpis. Nam eget sem nec erat rhoncus gravida. Nulla gravida velit non suscipit hendrerit. Curabitur gravida sit amet eros nec porttitor. Vestibulum in posuere ligula. Duis eu ultrices quam. Aenean consequat, libero ut tristique luctus, est nibh egestas sem, eget molestie lorem augue id dolor. Integer imperdiet placerat turpis blandit mollis.",
            "Phasellus id quam sed nisi scelerisque egestas nec congue ipsum. Ut dignissim elit non dolor pellentesque viverra. Praesent condimentum, magna id fermentum cursus, nibh eros suscipit dui, a sodales turpis est et elit. Nam sit amet mi vitae eros molestie pharetra. Phasellus ac ex ligula. Duis posuere, massa vel imperdiet ultricies, augue velit fermentum massa, quis varius nunc metus id nibh. Cras luctus scelerisque odio eget pharetra. Quisque ante massa, eleifend eu enim in, tristique condimentum massa. Morbi sed enim cursus, sodales sapien sit amet, consectetur erat. Morbi faucibus tincidunt tristique. Ut nec ligula suscipit, molestie urna id, lacinia nisi. Morbi quis diam convallis, mollis metus tincidunt, accumsan eros. Donec volutpat, nunc rutrum interdum tempor, velit lacus ullamcorper augue, vitae ornare nisi felis id augue. Etiam auctor feugiat luctus. Pellentesque luctus, nunc in gravida sagittis, diam nisl viverra risus, in efficitur ipsum sapien venenatis diam.",
            "Vestibulum euismod, turpis vitae sollicitudin cursus, quam enim tincidunt mi, ut congue quam ligula ut dui. Duis efficitur varius risus. Fusce cursus quam sem, vitae posuere lectus feugiat eget. Proin sit amet rhoncus arcu. Donec efficitur leo nec vestibulum lacinia. Fusce vitae ex lacinia, molestie neque sed, eleifend justo. Curabitur aliquet nibh vitae ligula convallis, et euismod sem gravida. Nam non tellus sed ligula imperdiet dignissim. In porta orci eu auctor laoreet. Donec efficitur eros id elit sagittis, nec condimentum massa dignissim. Curabitur varius accumsan arcu, ac venenatis arcu cursus quis. Pellentesque pellentesque, mi non congue placerat, magna lectus finibus purus, quis sagittis justo mi ut arcu. Duis id ante tristique, commodo erat et, eleifend elit. Donec in hendrerit dui. Quisque dapibus risus vehicula congue faucibus.",
            "In vitae metus turpis. Ut ullamcorper, magna nec congue ultrices, ipsum felis imperdiet est, ac tristique eros tellus id eros. Mauris feugiat nulla nec egestas tristique. Nulla commodo mauris lacus, sed feugiat neque sollicitudin eu. Curabitur pellentesque, nibh quis dignissim vestibulum, magna nisl laoreet orci, quis egestas nisi lorem nec quam. Ut a condimentum nulla. Quisque consequat, ligula ac ornare mattis, metus dolor consectetur ante, sed semper mi eros vel ex. Phasellus faucibus nunc quis mi blandit tristique. Etiam venenatis justo vitae tellus consequat tincidunt. Suspendisse pretium neque vel metus gravida, ut ullamcorper nulla suscipit. Vestibulum semper est eget nunc lacinia, sed dictum orci posuere. Donec fringilla dolor eu lorem tempor porta. Suspendisse fringilla euismod auctor.",
            "Duis ultrices tortor vitae eros consequat, at molestie lorem pharetra. Praesent mattis nunc cursus arcu sollicitudin accumsan. Maecenas ac tempus ante. Nullam et mollis odio. Fusce commodo, urna lobortis dapibus lobortis, ipsum felis vulputate tortor, et vehicula enim nulla quis mi. Cras maximus tempor purus, in vehicula libero pharetra non. Praesent suscipit imperdiet dui, sit amet vulputate dui. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque scelerisque viverra arcu vel ullamcorper. Nam rutrum, nisl vitae elementum rhoncus, ante leo luctus enim, eu porttitor libero arcu ut felis. Sed porta, metus ut placerat finibus, ipsum metus molestie quam, et faucibus elit turpis ac tellus. Integer ultrices consectetur laoreet.",
            "Aenean finibus massa a aliquet finibus. Cras ac blandit neque, eu auctor ligula. Nam semper leo lacus, eget rutrum nibh rhoncus ac. Mauris ut nibh ac elit consequat semper. Curabitur est nulla, rutrum ultricies mauris et, posuere viverra purus. Proin sollicitudin ut enim vitae bibendum. Suspendisse vel fringilla nisl, vehicula malesuada sapien. Vivamus dapibus pulvinar scelerisque. Morbi eu sem ut tellus porta dignissim sit amet suscipit elit.",
            "Vestibulum a ipsum a leo tempor lacinia ut et massa. Aenean aliquet commodo lacus, nec fermentum nulla commodo quis. Praesent mattis mauris nisl, ac lacinia nisi lacinia dignissim. Aenean porttitor suscipit nisi nec hendrerit. Donec ultricies a neque at egestas. Quisque at ullamcorper odio. Nunc cursus imperdiet tempus. Maecenas pellentesque ante ac tempor vulputate. Duis tincidunt mauris et nisi efficitur auctor.",
            "Etiam vel risus non odio faucibus sollicitudin vitae ac nunc. Aenean imperdiet mauris nibh, eu semper massa pretium in. Sed elit massa, egestas ac urna ut, lobortis fringilla nisi. Mauris congue tincidunt lorem, sit amet maximus risus placerat id. Integer auctor eros dolor, sed dictum quam varius quis. Nullam blandit mauris in arcu interdum dictum. Praesent volutpat ut eros vitae sagittis. Vivamus sit amet tellus a nibh sollicitudin vehicula. Aliquam feugiat purus nec arcu pellentesque sagittis. Sed a fermentum libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris sit amet scelerisque odio. Etiam iaculis consequat scelerisque.",
            "Pellentesque molestie libero felis, sed volutpat nulla consectetur vel. Ut ac magna nec sapien scelerisque egestas. Cras in vestibulum urna. Morbi hendrerit, tortor sed tincidunt luctus, felis turpis aliquam diam, vel rutrum diam turpis a lorem. Sed in ultricies elit, varius porttitor lorem. Curabitur tempus augue imperdiet, varius massa eu, consequat ipsum. Ut egestas a enim quis bibendum. Sed dignissim mi iaculis tellus cursus, at maximus urna egestas. Nam magna risus, tincidunt ornare efficitur id, pretium ut urna. Duis eu hendrerit nibh. Nam vestibulum augue sed euismod pulvinar. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
            "Duis sodales ultrices gravida. Mauris porta lacus non nibh vulputate, in varius sapien viverra. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi nec tellus consequat, semper nibh ac, euismod leo. Quisque ut finibus arcu. Cras ut quam ornare, tempor felis id, blandit velit. Praesent quis dui felis. Mauris non augue condimentum, dignissim erat a, dictum nibh. Cras consequat arcu nunc, suscipit feugiat sem faucibus et. Vivamus volutpat pharetra fermentum. Aenean quis ullamcorper libero. Pellentesque pretium porta elit non commodo. Pellentesque rutrum turpis tortor, id dapibus lacus molestie eu. Proin ac magna eros.",
            "Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque pulvinar ligula diam, ac mattis arcu posuere eu. Sed lacus magna, ultrices a est id, consectetur finibus nulla. In vitae nibh congue nisl malesuada scelerisque. Sed maximus, leo id sodales venenatis, enim nulla commodo massa, nec malesuada nisi arcu faucibus arcu. Integer blandit lacus ac purus sagittis iaculis. Ut eleifend nibh et suscipit cursus. Nam sit amet tellus vehicula, tempus elit non, elementum ex. Integer elementum, nisl quis ultricies faucibus, tellus mauris consequat felis, sit amet gravida nisi justo vel velit. Aliquam efficitur massa blandit nisl viverra viverra. Cras eros ex, malesuada posuere est at, congue tempor mi.",
            "Etiam leo nisi, dictum quis neque at, lobortis imperdiet erat. Pellentesque sit amet neque eu orci finibus ultricies sed nec elit. Maecenas augue nulla, sollicitudin eu malesuada eu, imperdiet in tellus. Donec finibus, odio ac finibus finibus, risus est auctor ex, laoreet laoreet erat nibh nec eros. Mauris mi metus, egestas at tortor sit amet, rutrum rhoncus nunc. Donec sem metus, porta eu varius a, ultrices non dui. Nunc ac metus et sapien pulvinar laoreet vel at lectus. In tristique malesuada lectus vel vehicula. Fusce scelerisque vestibulum eleifend.",
            "Aliquam erat volutpat. Nunc pellentesque velit ante, eu imperdiet purus scelerisque eu. Vivamus cursus porta posuere. Duis eros est, maximus in efficitur eget, finibus ac nulla. Nulla condimentum commodo sollicitudin. Curabitur pulvinar ex vitae pellentesque varius. Sed non rutrum dui. Phasellus sed nibh ullamcorper, euismod neque sit amet, auctor arcu. Phasellus nunc nunc, rhoncus sit amet venenatis at, elementum nec ipsum. Mauris elementum placerat sodales. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec condimentum metus massa, a euismod est dictum in. Morbi tincidunt pretium tellus. Sed egestas ex eu varius elementum. Nulla placerat placerat orci, vehicula faucibus arcu. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
            "Suspendisse porttitor, ipsum vel condimentum semper, nibh lorem facilisis dolor, vitae pulvinar elit tellus vel velit. Ut vulputate, elit sit amet dapibus sodales, neque ligula scelerisque erat, efficitur pretium enim ante sit amet est. Aenean vitae accumsan sapien. Pellentesque congue egestas odio ut tincidunt. Praesent ut vehicula nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur accumsan mi, non dignissim sem faucibus non. Quisque interdum arcu non dolor placerat euismod. Duis imperdiet lacinia sapien a dignissim. Suspendisse sed euismod urna. Vestibulum viverra eleifend sapien eu vehicula. Vivamus magna lectus, porta id efficitur ut, sagittis eget velit. Aenean tristique cursus nisi quis fermentum. Nunc eu posuere orci. Proin ornare sollicitudin diam ut fringilla.",
            "Sed rutrum ante dui, sit amet facilisis mi dignissim ut. Aliquam eleifend sagittis diam ut porttitor. In vel mi dignissim, blandit purus in, congue sem. Morbi et risus velit. Nunc pulvinar tortor gravida urna porta, a commodo ipsum pellentesque. Praesent aliquam sed sem ut consequat. Proin sed scelerisque urna.",
            "Ut purus nulla, maximus et metus nec, ultrices luctus augue. Nunc fringilla nec justo nec sagittis. Pellentesque iaculis fringilla ipsum eu accumsan. Aliquam orci lacus, malesuada ac accumsan sed, lobortis vel quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus lacinia velit ac aliquam viverra. Duis scelerisque eget turpis maximus ornare. Donec ultricies, dolor vitae iaculis auctor, tortor felis rhoncus neque, non volutpat augue mauris sit amet est. Donec gravida ut enim eu semper. Duis ut ornare metus, quis tincidunt nibh. Integer ut sapien vel magna posuere commodo ut nec libero. Cras interdum sit amet nibh et facilisis. Vestibulum scelerisque finibus ex eget rutrum. Mauris sed mi mattis, iaculis lorem eu, vestibulum leo. Pellentesque non molestie augue, sed tincidunt leo.",
            "Duis vitae mauris sapien. Vivamus erat sapien, congue vitae orci sed, congue congue urna. Proin vel congue magna, vitae semper lectus. Pellentesque tristique leo sit amet cursus aliquet. Suspendisse non vulputate lacus. Nullam laoreet, erat quis rhoncus aliquet, neque nisl pharetra risus, ut tempus velit odio ut lacus. Vestibulum finibus vehicula tellus, egestas viverra massa porttitor id. Integer eleifend sollicitudin diam ut imperdiet. Curabitur ac tellus non dui interdum sollicitudin. Nunc luctus tincidunt auctor. Ut pellentesque, leo fermentum accumsan rhoncus, leo metus iaculis nisi, non blandit lacus ipsum a nunc. Sed maximus efficitur lorem, sit amet viverra ante. Aenean ornare ultricies lorem, sed placerat ante sollicitudin a.",
            "Sed volutpat quis leo eu ultricies. Sed pharetra nibh est, in molestie tellus porttitor id. Nunc turpis nulla, consequat vitae augue ut, ultricies auctor odio. Donec a euismod diam. Mauris mollis, libero ac gravida hendrerit, urna risus porta lectus, eu lobortis ante tellus nec enim. Donec pellentesque tempus dolor ac posuere. In quis tristique neque. Nunc ut dolor suscipit, fermentum lectus eu, pulvinar eros. Etiam ornare eu felis quis lacinia.",
            "Nullam varius vulputate tellus, eget luctus justo vestibulum nec. Sed viverra accumsan ex eu iaculis. Vestibulum eget dolor lobortis, malesuada lorem maximus, aliquet nulla. Pellentesque id varius dui. Nulla sed consequat lorem. Sed in turpis congue, semper elit sed, porttitor diam. Maecenas suscipit magna eu gravida iaculis. Quisque suscipit est sed dui consectetur facilisis.",
            "Proin efficitur pharetra metus vitae varius. Donec ut mauris a eros dictum ultricies. Etiam viverra massa eu libero pharetra, efficitur maximus dui malesuada. Sed nec porttitor augue, vitae tincidunt mi. Etiam ut finibus ligula. Mauris sollicitudin vel magna id vestibulum. Sed sit amet congue justo. Nulla posuere ex gravida pretium eleifend. Nam tincidunt id metus nec commodo. Praesent at egestas massa, ultrices molestie urna. Suspendisse urna sem, sagittis tristique massa placerat, rutrum fringilla nisl. Suspendisse ultricies felis ut arcu tempor sodales. Maecenas posuere posuere enim, in bibendum tellus maximus et. In lectus dolor, vulputate eget erat nec, pellentesque facilisis justo. Phasellus a velit bibendum, cursus ex vitae, finibus est.",
            "Nullam hendrerit sodales vulputate. Ut vitae sapien quis sapien sodales semper. Vivamus porta commodo varius. Proin eleifend finibus tempor. Mauris dapibus est vel urna venenatis, a eleifend ipsum posuere. Nam velit mi, pretium vitae est et, pharetra vestibulum purus. Integer dapibus magna sed justo hendrerit, non consectetur orci viverra. Vivamus at faucibus justo, vitae pellentesque mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque nec tempus ipsum. Pellentesque pharetra tristique porttitor. Suspendisse potenti. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed eu mattis neque, a condimentum diam.",
            "Nunc vulputate augue non commodo feugiat. In pellentesque sem vitae tincidunt luctus. Nunc eleifend maximus ullamcorper. Sed sagittis fringilla convallis. Praesent eleifend vel magna a maximus. Quisque quis porta lectus. Mauris quis diam nec sapien dignissim tincidunt ut ut ex. Cras mauris enim, mollis in sagittis vitae, bibendum et nisl. Phasellus euismod, nisl ut vulputate iaculis, lacus erat pellentesque diam, in imperdiet velit mauris ut lectus. Donec ullamcorper neque et ligula iaculis ultrices.",
            "Sed lobortis, mi eget tincidunt convallis, sem lectus pulvinar urna, consectetur facilisis diam felis quis turpis. Morbi vestibulum, magna in ultrices sagittis, mi velit finibus ligula, eu molestie est turpis tempor eros. Donec efficitur aliquam dolor. Maecenas laoreet rhoncus mauris. Sed facilisis porta velit id mattis. Integer leo erat, tempus sed ante ut, ornare condimentum enim. Praesent convallis turpis non tincidunt facilisis. Vestibulum dolor ipsum, dictum in dapibus vel, ultricies ac ante. Nullam blandit risus nisl, vitae sollicitudin justo egestas a. Vestibulum scelerisque, massa sed lobortis consequat, mi mi sagittis dolor, eget posuere neque odio ac tellus.",
            "Suspendisse pretium felis vitae eros volutpat, nec varius odio euismod. Suspendisse eu mauris auctor, venenatis erat eget, mollis nunc. In a orci non eros vehicula elementum a a augue. Maecenas pretium eros quis tellus tristique lacinia. Quisque suscipit nisi ac iaculis ultrices. Proin malesuada, elit non scelerisque pellentesque, justo metus hendrerit orci, id pulvinar nisl lectus at mauris. Nam tellus libero, vestibulum sed velit non, malesuada pretium dui.",
            "Nullam bibendum at sem vel malesuada. Sed lectus dolor, euismod sed consectetur ut, dictum non ipsum. Ut quis cursus magna, sit amet mollis augue. Fusce porttitor feugiat justo vel consequat. Cras vehicula tempus nulla id euismod. Quisque lobortis nibh est, congue ultrices odio lobortis sed. Vestibulum quis consequat sem. Curabitur at feugiat eros, et eleifend orci.",
            "Duis luctus dignissim bibendum. Nulla turpis ante, auctor non magna dictum, pharetra bibendum risus. Aliquam pretium risus ante, et finibus ipsum ornare a. Duis pharetra nunc et lectus tristique maximus quis sit amet nulla. Mauris vitae aliquam lacus. Duis iaculis, sapien vel rhoncus ultrices, mauris nisi vehicula ipsum, quis rutrum magna mi ut risus. Pellentesque id massa vitae nibh accumsan lacinia in in velit. Nam commodo mollis mauris laoreet condimentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque eget sapien sed diam iaculis dignissim. Mauris et scelerisque ex, ac suscipit arcu. Proin eu quam velit. Nunc pulvinar urna vitae turpis interdum imperdiet. Maecenas libero diam, tincidunt in nunc et, imperdiet pulvinar ex. Fusce eleifend eget enim at lacinia.",
            "Sed elementum, massa id mattis vulputate, ipsum sem efficitur ipsum, at posuere elit erat eu mauris. Curabitur posuere augue eu nisi sollicitudin, et sagittis neque lacinia. Integer sit amet ipsum libero. Maecenas laoreet mauris eros, quis tincidunt lorem accumsan in. Donec sit amet luctus tellus. Donec eu tristique odio. In cursus semper eleifend. Proin tristique eros vitae commodo hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse ultricies et sapien non efficitur. Donec ligula velit, condimentum sed ullamcorper sed, mattis placerat justo. Quisque nec sodales nibh. Proin vitae diam turpis. Quisque leo metus, lobortis ac arcu sed, cursus cursus tellus.",
            "Nunc lacinia viverra velit, ut ultrices turpis volutpat vel. Nunc tristique tincidunt sapien, id accumsan nisl accumsan eget. Phasellus rhoncus volutpat dolor, in viverra nibh. Ut id odio sit amet ligula iaculis sollicitudin. Phasellus quis egestas magna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean orci sem, viverra nec est mollis, efficitur hendrerit dui. Nulla tempor orci et lacus faucibus, at varius diam tincidunt. In ut est fermentum, rutrum diam nec, finibus dui. Etiam eu lacus pellentesque, sodales ex in, vulputate nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut tincidunt est eget auctor vestibulum.",
            "In tincidunt congue tortor, ut tincidunt arcu scelerisque sed. Praesent interdum dignissim nisi ullamcorper accumsan. Curabitur ullamcorper eu orci eu commodo. Proin condimentum, sapien faucibus bibendum pharetra, enim urna auctor tellus, vel pellentesque mi ante eget justo. Mauris gravida imperdiet malesuada. Nullam imperdiet tincidunt est nec pellentesque. Curabitur at ultrices nulla. Morbi cursus euismod elit eget convallis. Praesent nec cursus orci. Quisque condimentum at dolor sed tempus.",
            "Nunc in condimentum est, id feugiat libero. Integer eu arcu viverra, ornare nibh vel, vulputate dolor. Maecenas leo justo, rhoncus eu leo in, commodo sagittis neque. Ut quis vehicula elit. Maecenas ante felis, pharetra eu accumsan nec, malesuada vel velit. Etiam ultrices tortor sit amet nisl venenatis, ac finibus sapien congue. Cras imperdiet, tortor malesuada blandit pulvinar, purus libero eleifend felis, a euismod mi metus a odio. Vivamus non fermentum sem. Morbi condimentum magna tortor. Donec in libero ac velit malesuada vestibulum. Duis at neque mi. Cras gravida efficitur sem at rutrum. Vestibulum dictum ligula a augue egestas, nec vehicula mi hendrerit. Donec pulvinar dui non ipsum dictum, faucibus posuere libero efficitur.",
            "Donec viverra facilisis justo sed rutrum. Donec eget ex sodales, tempus nisl ut, rhoncus ipsum. Cras mollis augue vitae aliquet bibendum. Nam sollicitudin fringilla ligula in interdum. Mauris efficitur tincidunt justo, vitae tristique tortor pulvinar egestas. Duis neque turpis, commodo sed vestibulum vitae, rutrum sed arcu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce dictum orci placerat, semper turpis eu, placerat arcu. Integer sed enim sit amet odio mollis sodales. Phasellus in dui sed nibh convallis convallis. Phasellus rutrum in urna quis tincidunt. Duis facilisis elit sapien, et blandit massa ullamcorper eu. Sed quis blandit tellus. Cras vulputate, erat porta vestibulum bibendum, leo diam fermentum lorem, vel viverra eros enim quis dolor. Praesent id scelerisque quam. Duis dapibus tempus convallis.",
            "Nunc nec neque rutrum, lobortis nibh ac, imperdiet leo. Proin vehicula vestibulum semper. Sed vel imperdiet ligula. Cras rhoncus ac diam sed auctor. Suspendisse sed tellus malesuada, tempor purus imperdiet, accumsan dolor. Phasellus eu facilisis mi. Quisque lacinia, tellus quis vestibulum condimentum, lacus nisi bibendum lectus, vitae porta risus erat vel purus. Suspendisse pharetra justo eu convallis aliquet.",
            "Sed tempor justo nec rhoncus varius. Nullam molestie dui magna, vitae semper purus consectetur vel. Donec aliquam sit amet velit eget commodo. Morbi faucibus sed sem ac faucibus. Nullam vehicula id lorem quis viverra. Nunc pulvinar fringilla nunc vel lacinia. Curabitur ut ornare metus. Nulla id bibendum justo, a feugiat sapien. Praesent gravida porta tortor nec maximus. Morbi nec maximus dui. Nullam non auctor dui. Sed dignissim efficitur risus cursus malesuada. Donec consequat dolor ut augue elementum hendrerit. Ut neque massa, finibus non porta sed, porta sed justo. Nunc pretium, lacus ut pulvinar pharetra, tortor justo rhoncus metus, vel sagittis lorem turpis eget massa. Quisque lobortis ipsum sed elementum venenatis.",
            "Maecenas ut cursus eros, laoreet semper felis. Maecenas pretium placerat quam vitae pharetra. Nulla porttitor in mi at dapibus. Nulla interdum scelerisque elit vitae eleifend. Nunc mattis pellentesque nunc, vitae consectetur nisi lobortis blandit. Aenean vel ligula nec eros porta mattis. Fusce vitae euismod libero, sit amet blandit nisl. Suspendisse gravida pretium nisi. Nulla feugiat sit amet erat in fermentum. Ut sed augue leo. Aliquam erat volutpat.",
            "Proin id purus quis eros sodales mollis. Fusce posuere nisi ligula, id pharetra nulla malesuada at. Mauris pharetra velit at convallis dictum. Nunc varius convallis magna, ac consequat ligula commodo sit amet. Nulla facilisi. Curabitur vestibulum urna vitae libero auctor congue. Proin lacus est, interdum id volutpat ut, convallis in metus. Nunc bibendum, enim eget venenatis placerat, augue nibh condimentum tellus, eu euismod elit tortor quis lorem.",
            "Vestibulum ornare molestie lacus vitae convallis. Sed convallis dapibus purus. Nullam faucibus eros nec mollis fringilla. Fusce non elementum nisl. Sed a ante id mi ultrices pulvinar quis nec mi. Vestibulum eget sem ac nibh aliquet rhoncus non et mauris. Nullam tempor mattis congue. In ac pharetra enim. Curabitur sagittis rutrum magna a rutrum.",
            "Nulla rutrum viverra odio, vel imperdiet nunc dictum ac. Quisque ac ligula molestie, bibendum tellus vitae, faucibus nisl. Mauris bibendum cursus consequat. Proin rutrum, ante a imperdiet efficitur, dolor neque tempus eros, non fermentum arcu sapien quis neque. Sed venenatis consequat risus, ac euismod ipsum tincidunt at. Mauris congue lacus eros, sit amet dignissim ante vestibulum eu. Quisque bibendum pulvinar tincidunt.",
            "Aliquam facilisis luctus nibh, eget dapibus quam euismod nec. Quisque in gravida libero. Aenean hendrerit massa eget nunc facilisis gravida. Integer pretium interdum sem id pharetra. Nulla facilisi. Maecenas ultricies sem ac urna imperdiet, vel aliquet augue eleifend. Donec fermentum, risus at molestie dictum, enim tellus sodales enim, vitae congue neque nisi id purus. Pellentesque auctor, ipsum vitae auctor rutrum, nulla massa iaculis urna, a pharetra nibh ligula vitae lectus.",
            "Sed et dolor sodales, mollis dolor at, vulputate tortor. Sed dictum turpis at tortor auctor convallis. In nec varius turpis. Sed auctor elementum nulla vel sagittis. Donec a lacus interdum, ornare tortor ac, faucibus sem. Nam bibendum pulvinar purus at commodo. Curabitur eget mi nisl. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aenean mollis ullamcorper scelerisque. Aliquam convallis neque erat, quis dictum diam molestie et. Nullam quis lectus egestas, pellentesque ante eu, congue est. Fusce luctus dolor quam, non luctus libero ultricies sit amet. Donec vitae neque odio.",
            "Nunc faucibus commodo ante, eu pharetra lorem rhoncus eu. Aliquam lacinia, ante id sagittis hendrerit, magna quam convallis urna, non pharetra quam dolor eu leo. Sed blandit arcu felis, vitae viverra risus aliquam at. Nulla interdum, nisi nec ultricies eleifend, felis magna pretium risus, vel porttitor velit arcu feugiat neque. Integer egestas metus eu dignissim vulputate. Sed maximus magna sit amet est dapibus, vitae hendrerit ligula rhoncus. Phasellus accumsan auctor turpis, ut vulputate mauris vulputate ut.",
            "Phasellus lacinia nisi eget arcu sodales mattis. Donec felis ligula, rhoncus at euismod sit amet, cursus ut felis. Aenean a lacus rutrum, commodo enim id, rhoncus sem. Nulla pretium arcu interdum, congue eros vel, dignissim velit. Fusce feugiat tristique dui nec varius. In iaculis lorem nisl, a congue lacus ultrices eu. Curabitur posuere nibh id odio euismod, in lacinia tortor tristique. Duis blandit maximus suscipit. Sed vel orci rhoncus, rhoncus eros vitae, pulvinar odio. Duis a tellus in massa feugiat efficitur. Phasellus dictum velit purus, non fermentum sapien blandit in. Mauris vel lacinia purus. Phasellus quis sagittis metus.",
            "Nam lacinia dapibus mauris, in elementum nulla pellentesque nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris consectetur luctus cras amet."
        ];

        return sentences.join('<br>');
    }

    return {
        sentence: sentence,
        paragraph: paragraph
    };

})();

exports.LoremIpsum = LoremIpsum;